### ISSUE TITLE
「白夜行」- 东野圭吾

### ISSUE THREAD

**Issue by fundon** [fundon/fundon.github.io#41]
# 白夜行

> 我的天空没有太阳，总是黑夜，但并不暗，因为有东西替代了太阳。虽然没有太阳那么明亮，但对我来说已经足够。
> 凭借着这份光，我便能把黑夜当成白天。
> 我从来就没有太阳，所以不怕失去。

http://book.douban.com/subject/10554308/

感想：

> 在白夜，看不到影子，也没有灵魂。

**Comment by ghost** [comment]
:cry: 我比你懒得多, 我是这样的

https://github.com/haoxins/blogs/issues/5

后来再也没写过了 :cry:

**Comment by fundon** [comment]
哈哈，够懒

我也就随手记录下 😬
